# Generated by Django 5.2.3 on 2025-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editar', models.TextField(verbose_name='editar')),
                ('eliminar', models.TextField(verbose_name='eliminar')),
                ('modificar', models.TextField(verbose_name='modificar')),
                ('rol_id', models.TextField(verbose_name='rol_id')),
                ('agregar', models.TextField(verbose_name='agregar')),
            ],
        ),
    ]
