# Generated by Django 5.2.3 on 2025-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_servicio', models.TextField(verbose_name='tipo_de_servicio')),
                ('tiempo_de_servicio', models.TextField(verbose_name='tiempo_de_servicio')),
            ],
        ),
    ]
