# Generated by Django 5.2.3 on 2025-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_id', models.TextField(verbose_name='total_id')),
                ('total_a_pagar_id', models.TextField(verbose_name='total_a_pagar_id')),
                ('tipo_de_servicio_id', models.TextField(verbose_name='tipo_de_servicio_id')),
            ],
        ),
    ]
