# Generated by Django 5.2.3 on 2025-07-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.TextField(verbose_name='placa')),
                ('servicio_id', models.TextField(verbose_name='sercicio_id')),
                ('hora_y_fecha_de_enytada', models.TextField(verbose_name='hora_Y_fecha_de_entrada')),
            ],
        ),
    ]
